jQuery(document).ready(function($){const btnMuaNgay=jQuery("#btn-mua-ngay"),customerInfo=jQuery(".customer_info"),btnDatHang=jQuery("#btn-dat-hang");btnMuaNgay.click(function(e){btnMuaNgay.addClass("hidden");customerInfo.removeClass("hidden");});$.validator.addMethod("valid_phone",function(value,element){return!/(03|05|07|08|09)+([0-9]{8})\b/.test(value)?false:true;},"Sá»‘ Ä‘iá»‡n thoáº¡i khĂ´ng Ä‘Ăºng Ä‘á»‹nh dáº¡ng");function setCookie(cookieName,cookieValue,expirationDays){var d=new Date();d.setTime(d.getTime()+(expirationDays*24*60*60*1000));var expires="expires="+d.toUTCString();document.cookie=cookieName+"="+cookieValue+"; "+expires+"; path=/";}
function getCookie(name){var nameEQ=name+"=";var ca=document.cookie.split(';');for(var i=0;i<ca.length;i++){var c=ca[i];while(c.charAt(0)==' ')c=c.substring(1,c.length);if(c.indexOf(nameEQ)==0)return c.substring(nameEQ.length,c.length);}
return null;}
customerInfo.find('#customer_name').val(getCookie('sdh_dat_hang_customer_name'))
customerInfo.find('#address').val(getCookie('sdh_dat_hang_address'))
customerInfo.find('#phone').val(getCookie('sdh_dat_hang_phone'))
customerInfo.validate({rules:{customer_name:{required:true,},address:{required:true,},phone:{required:true,valid_phone:$("#phone").val()},payment_method:{required:true,}},errorPlacement:function(error,element){if(element.is(":radio")){error.appendTo(element.parents('.payment_method'));}else{error.insertAfter(element);}},messages:{customer_name:{required:"ThĂ´ng tin báº¯t buá»™c"},address:{required:"ThĂ´ng tin báº¯t buá»™c"},phone:{required:"ThĂ´ng tin báº¯t buá»™c"},payment_method:{required:"ThĂ´ng tin báº¯t buá»™c"}},submitHandler:function(form,e){e.preventDefault();let formData=$(form).serializeArray().reduce(function(json,{name,value}){json[name]=value;return json;},{});$.ajax({type:'POST',url:myAjax.ajaxurl,data:{action:'sdh_dat_hang_submit',nonce:myAjax.nonce,...formData},beforeSend:function(){customerInfo.addClass('processing').append(`<div class="blockUI" style="display:none"></div><div class="blockUI blockOverlay" style="z-index: 1000; border: none; margin: 0px; padding: 0px; width: 100%; height: 100%; top: 0px; left: 0px; background: rgb(255, 255, 255); opacity: 0.532649; cursor: default; position: absolute;"></div><div class="blockUI blockMsg blockElement" style="z-index: 1011; display: none; position: absolute; left: 525px; top: 449px; cursor: default;"></div>`);btnDatHang.addClass("loading");setCookie("sdh_dat_hang_customer_name",customerInfo.find('#customer_name').val(),30);setCookie("sdh_dat_hang_address",customerInfo.find('#address').val(),30);setCookie("sdh_dat_hang_phone",customerInfo.find('#phone').val(),30);},success:function(response){if(response.success){const url_redirect=response.data.url_redirect
const payment_method=response.data.payment_method
if(payment_method==='COD'){location.assign(response.data.url_redirect)}
if(response.data.payment_method==='FUNDIIN'){Swal.fire({icon:`success`,title:`Táº¡o Ä‘Æ¡n hĂ ng tráº£ gĂ³p qua Fundiin thĂ nh cĂ´ng`,text:`Báº¡n sáº½ Ä‘Æ°á»£c chuyá»ƒn Ä‘áº¿n trang Fundiin Ä‘á»ƒ hoĂ n thĂ nh thá»§ tá»¥c tráº£ gĂ³p.`,allowOutsideClick:false,allowEscapeKey:false,allowEnterKey:false,}).then((result)=>{setTimeout(function(){location.assign(url_redirect)},500)});}}},error:function(xhr){console.log('Error: ',xhr.responseText)
Swal.fire({icon:'error',text:'CĂ³ lá»—i xáº£y ra, vui lĂ²ng liĂªn há»‡ vá»›i bá»™ pháº­n há»— trá»£.',});},
complete:function(){$('.mfp-close').click();
customerInfo.find('.blockUI').remove();customerInfo.removeClass('processing');btnDatHang.removeClass("loading");}});}});const featuredHot=document.querySelectorAll(".featured-products-of-the-brand");featuredHot.forEach((e=>{if(e.querySelector(".box-text-bottom").clientHeight>110){e.classList.add("open","less");const s=e.querySelector(".more-parm");if(!s)return false;s.addEventListener("click",(()=>{s.classList.contains("less-parm")?(e.classList.add("less"),s.classList.remove("less-parm"),s.innerHTML="Xem ThĂªm"):(s.classList.add("less-parm"),e.classList.remove("less"),s.innerHTML="Thu Gá»n")}))}}));window.addEventListener("load",(event)=>{if(typeof promotionPanels!='undefined'){document.querySelectorAll("div.fundiin-promotion__panel").forEach(e=>{if(e.nextSibling.tagName=='BR'){e.nextSibling.remove()}
e.remove()})}});});